### ISSUE TITLE
Fix failing CI build

### ISSUE THREAD

**Issue by demisx** [frequency-chain/docs#30]
The [build job](https://github.com/LibertyDSNP/frequency-docs/runs/8080275502?check_suite_focus=true) is failing on the first run. I believe there may be a racing condition between the artifacts being available and another job trying to download them. Especially, taking into consideration that the job usually passes on a second run.

```sh
Run dawidd6/action-download-artifact@v2
==> Repository: LibertyDSNP/frequency-docs
==> Artifact name: 
==> Local path: ./
==> Workflow name: mdbook_ci.yml
==> Workflow conclusion: success
==> Commit: 2fd57[10](https://github.com/LibertyDSNP/frequency-docs/runs/8080275502?check_suite_focus=true#step:3:11)6716c972a6900c4b[15](https://github.com/LibertyDSNP/frequency-docs/runs/8080275502?check_suite_focus=true#step:3:16)670abbd151be0b4

Error: no matching workflow run found with any artifacts?
```

### Steps to reproduce
1. Modify the triggers in CI/CD workflows to kick-in on dev branch
2. Push some changes to remote

### Expected behaviour
The job should pass each time

### Actual behaviour
The `build` job in "Frequency Docs MDBook CD" workflow fails on first run

### Any other comments?
Wondering why we need to split such a simple workflow in two coupled workflows to begin with. 🤔 

References:
- [Storing workflow data as artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts)

**Tasks:**
- [x] Analyze the problem
- [x] Suggest solution and collect feedback
- [x] Implement solution
- [x] Port solution to https://github.com/LibertyDSNP/spec/tree/main/.github/workflows ([Created new issue](https://github.com/LibertyDSNP/spec/issues/202))

**Comment by wilwade** [comment]
@demisx I thought the merged pr wasn't triggering the CI part of the build. Perhaps that is the actual issue? CD should be taking the artifact from the last PR build, but if it is re-triggering the build, that would cause the race condition.

If we did switch to the proposed flow, we will still need to build the mdbook in in the verification workflow because it does additional checks that just linting doesn't do.
