### ISSUE TITLE
Docs Final Review

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/docs#87]
- [x] Double check mobile
- [x] Double check print styles
- [x] Design Pair
- [x] bottom nav button highight
- [x] button-links needs a better hover
- [x] #105 Prev/next chapter buttons are off-center due to the left menu nav (might just need to pad the right hand side)
- [x] #104
- [x] Dark version of the header and footer
- [x] Readability is not consistent: The inner container seems to be sizing in and out based on content aka something needs a width 100% somewhere
- [x] Double check that the developer portal button should have the active state? Nope
- [x] Expand the minimum size of the center "row" so that the page always scrolls some when on a short browser.
- [x] https://github.com/frequency-chain/docs/issues/101
- [x] #102
- [x] Fixed in #97 Hide header on print
- [x] Fixed in #97 There's about a 20px gap at 800px-819px where the mobile nav looks funny though, it's at an iPad width when the `Dev Docs` link goes to two lines.
- [x] Think about using local storage to store the sidebar width across links (Not now)
- [x] Header logo should at least start centered over the nav bar
- [x] Remove the teal on blue
